### ISSUE TITLE
大佬, 请问底部的powered by alibaba怎么除去

### ISSUE THREAD

**Issue by jaythc** [ionething/fuck-druid-ad#1]
![](https://user-images.githubusercontent.com/29886008/52836258-ff1a2d00-3124-11e9-9402-41bcf2e75fd0.png)

**Comment by ionething** [comment]
原理和去除广告一样，主要看源码footer是写在html还是js的，然后处理。建议按照开源协议来使用，强烈不建议去掉版权页。
